name: CI

on:
  push:
    branches: [ 'main' ]
    paths:
    - 'apps/plagiarism-service/**'
    - '.github/workflows/ci-rust.yaml'
    - 'rust-toolchain.toml'
  pull_request:
    paths:
    - 'apps/plagiarism-service/**'
    - '.github/workflows/ci-rust.yaml'
    - 'rust-toolchain.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
  CI: true
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-Dwarnings -C debuginfo=0"

defaults:
  run:
    shell: bash
    working-directory: apps/plagiarism-service

jobs:
  lint-rust:
    name: Code quality Rust
    runs-on: blacksmith-4vcpu-ubuntu-2204
    environment: lumio
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install Rust toolchain
      uses: moonrepo/setup-rust@v1
      with:
        components: clippy,rustfmt
        cache-base: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check formatting
      run: cargo fmt --all --check
      env:
        MINIO_ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
        MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        MINIO_BUCKET: ${{ vars.MINIO_BUCKET }}

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
      env:
        MINIO_ENDPOINT: ${{ vars.MINIO_ENDPOINT }}
        MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
        MINIO_BUCKET: ${{ vars.MINIO_BUCKET }} 