services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9095:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=https://lumio-prometheus.jayllyz.fr"
      - "--web.route-prefix=/"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3100:3000"
