name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
  CI: true
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb
  TURBO_SCM_BASE: ${{ github.event.pull_request.base.sha }}
  CARGO_TERM_COLOR: always
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-Dwarnings -C debuginfo=0"
  REGION: ${{ secrets.REGION }}
  MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

jobs:
  test:
    name: Build and test
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      contents: read

    services:
      postgres:
        image: rapidfort/postgresql-official:17.5-alpine3.21
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
        - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    # Used to check if any files related to Rust have changed
    - name: Check for Rust-related changes
      id: changed-files
      uses: tj-actions/changed-files@v46
      with:
        files: |
          .github/workflows/ci.yaml
          rust-toolchain.toml
          justfile
          apps/plagiarism-service/**

    - name: Install Rust toolchain
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: moonrepo/setup-rust@v1
      with:
        bins: cargo-nextest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Cache turbo build setup
      uses: useblacksmith/cache@v5
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Generate Prisma && Prepare database
      run: bun run prisma

    - name: Build
      run: bun run build:ci

    - name: Run tests
      run: bun run test:ci

  lint:
    name: Code quality
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Biome
      uses: biomejs/setup-biome@v2

    - name: Run Biome
      run: biome ci .
